# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "nXl7xpJsZNBqq+T/mPlGigu19+rYCOAXxUjwfkym4zHbB0M3lO90fSuWTQ14H/37vk4A1JuLsHs6l77Z4rSrr5yHFPpQO1DcYVFz2+eh8psfkVIQmxQw4D8YXO2skG7PWXBCBf97ysxoaY2wTTyt+unvLNu8FgZI418DqtbmFGP7pilWqgrRnQ7ndqw9PB5Jv/ESKuqjvNpsluvhKhgfmIgQR36rL1oHXLmH5zAJBmYx05lulBjBp6Q1IMt80L0038wDnS/k13suapp7iJ/TnJdZ/r3slitZ/dD5NPPDd7+1wgsvOnyofvvlTdhsT0O+HUjiitWgAEjk3W1ux6FDVeVZhFQsNW4jd8veYa0sfCo1mro78OEL1QrLyFNIiXbNYTIANuC45VRFN3NzQm5ngl5G5BQEDjV9yKbpPZpI6wEq6bvUPTqwsltLuaQDbcqgcUn8EFdvLhUolhJr17rZqHr85jE8TKcboLTdSSRqdaiT2Gar1npPcJ935DnOhCfmeLEdG+lkTkuWfbBUWJpLHnkc6XhVQGDjh7yOmaVivtheE6O6NRaMX+WjlEvijDC+KqGjUl7x7l3QqZkNKM0Dj5WtW/mccSpO+T9LOoqUxqJd3ViGgpU8ERZyRrz8oO4jMF5EURBpxGi25NmetS56cTfPsqQGmWEo2uqECItYVyI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
